import {
  Analytics,
  Api,
  Bot,
  Chat,
  Choices,
  Code,
  Clean,
  Cloud,
  CloudDownload,
  CloudUpload,
  DeliveryTruck,
  Document,
  Download,
  Email,
  EventSchedule,
  Filter,
  FlowData,
  Fork,
  Idea,
  Launch,
  Notification,
  Power,
  Restart,
  Rocket,
  Save,
  Search,
  Settings,
  Task,
  Terminal,
  Time,
  TrashCan,
  Tools,
  Upgrade,
  Upload,
  User,
} from "@carbon/react/icons";
// eslint-disable-next-line
export default [
  { Icon: Analytics, name: "analytics" },
  { Icon: Api, name: "api" },
  { Icon: Bot, name: "bot" },
  { Icon: Chat, name: "chat" },
  { Icon: Choices, name: "choices" },
  { Icon: Code, name: "code" },
  { Icon: Clean, name: "clean" },
  { Icon: Cloud, name: "cloud" },
  { Icon: CloudDownload, name: "cloud download" },
  { Icon: CloudUpload, name: "cloud upload" },
  { Icon: DeliveryTruck, name: "delivery" },
  { Icon: Document, name: "document" },
  { Icon: Download, name: "download" },
  { Icon: Email, name: "Email" },
  { Icon: Idea, name: "idea" },
  { Icon: EventSchedule, name: "schedule" },
  { Icon: Filter, name: "filter" },
  { Icon: FlowData, name: "flow" },
  { Icon: Fork, name: "fork" },
  { Icon: Launch, name: "external" },
  { Icon: Notification, name: "notify" },
  { Icon: Power, name: "power" },
  { Icon: Restart, name: "restart" },
  { Icon: Rocket, name: "rocket" },
  { Icon: Save, name: "save" },
  { Icon: Search, name: "search" },
  { Icon: Settings, name: "settings" },
  { Icon: Task, name: "task" },
  { Icon: Terminal, name: "terminal" },
  { Icon: Time, name: "time" },
  { Icon: Tools, name: "tools" },
  { Icon: TrashCan, name: "delete" },
  { Icon: Upgrade, name: "upgrade" },
  { Icon: Upload, name: "upload" },
  { Icon: User, name: "user" },
];
