import { CloseOutline32, CheckmarkOutline32, Error32, Timer32 } from "@carbon/icons-react";

export const ACTIVITY_STATUSES = {
  COMPLETED: "completed",
  FAILURE: "failure",
  IN_PROGRESS: "inProgress",
  NOT_STARTED: "notstarted",
  INVALID: "invalid",
  SKIPPED: "skipped"
};

export const ACTIVITY_STATUSES_TO_INDEX = [
  ACTIVITY_STATUSES.IN_PROGRESS,
  ACTIVITY_STATUSES.COMPLETED,
  ACTIVITY_STATUSES.FAILURE,
  ACTIVITY_STATUSES.INVALID
];

export const ACTIVITY_STATUSES_TO_TEXT = {
  [ACTIVITY_STATUSES.COMPLETED]: "Succeeded",
  [ACTIVITY_STATUSES.FAILURE]: "Failed",
  [ACTIVITY_STATUSES.IN_PROGRESS]: "In Progress",
  [ACTIVITY_STATUSES.NOT_STARTED]: "Not Started",
  [ACTIVITY_STATUSES.INVALID]: "Invalid",
  [ACTIVITY_STATUSES.SKIPPED]: "Skipped"
};

export const ACTIVITY_STATUSES_TO_ICON = {
  [ACTIVITY_STATUSES.COMPLETED]: CheckmarkOutline32,
  [ACTIVITY_STATUSES.FAILURE]: CloseOutline32,
  [ACTIVITY_STATUSES.IN_PROGRESS]: Timer32,
  [ACTIVITY_STATUSES.NOT_STARTED]: Timer32,
  [ACTIVITY_STATUSES.INVALID]: Error32,
  [ACTIVITY_STATUSES.SKIPPED]: Error32
};
